pekko {
  actor {
    provider = "cluster"

    serializers {
      jackson-cbor = "org.apache.pekko.serialization.jackson.JacksonCborSerializer"
    }

    serialization-bindings {
      "org.twostack.libspiffy4j.serialization.SpiffyEvent" = jackson-cbor
    }
  }

  remote.artery {
    canonical.hostname = "127.0.0.1"
    canonical.port = 0
  }

  cluster {
    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"

    sharding {
      number-of-shards = 30
    }
  }

  persistence {
    journal.plugin = "jdbc-journal"
    snapshot-store.plugin = "jdbc-snapshot-store"
  }
}

pekko-persistence-jdbc {
  database-provider-fqcn = "org.twostack.libspiffy4j.config.HostDataSourceProvider"

  shared-databases {
    slick {
      profile = "slick.jdbc.PostgresProfile$"
      db {
        connectionPool = "disabled"
      }
    }
  }
}

jdbc-journal {
  use-shared-db = "slick"
}

jdbc-snapshot-store {
  use-shared-db = "slick"
}

jdbc-read-journal {
  use-shared-db = "slick"
}
